development:
  eventbrite:
    app_key: <%= ENV['EVENTBRITE_APP_KEY'] %>
    user_key: <%= ENV['EVENTBRITE_USER_KEY'] %>
    organizers:
      - "Software Hamilton"
      - "Coworking Niagara"
      - "SMC Niagara"